// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace AzureSaturdayPerth2015Api.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201505010457146_AddEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
